apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstoneproject-deployment
  labels:
    app: capstoneproject-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: capstoneproject-app
  template:
    metadata:
      labels:
        app: capstoneproject-app
    spec:
      containers:
        - name: capstoneproject-app
          image: mohramadan911/mycapstoneproject
          ports:
            - containerPort: 80

