- name: Copy deployment 
  shell: "sudo cp {{ ENVIRONMENT_NAME }}-deployment.yaml ../"
  # copy:
  #   src: "../files/{{ ENVIRONMENT_NAME }}-deployment.yaml"
  #   dest: $HOME

- name: Apply deployment 
  shell: "kubectl apply -f {{ ENVIRONMENT_NAME }}-deployment.yaml"
  args:
    chdir: $HOME
