- name: Copy deployment 
  # shell: "cp {{ ENVIRONMENT_NAME }}-deployment.yml $HOME" 
  copy:
    src: "{{ ENVIRONMENT_NAME }}-deployment.yml"
    dest: $HOME
- name: Apply deployment 
  shell: "./bin/kubectl apply -f {{ ENVIRONMENT_NAME }}-deployment.yml"
  args:
    chdir: $HOME
