apiVersion: v1
kind: Service
metadata:
  name: capstoneproject-app
spec:
  type: LoadBalancer
  selector:
    app: capstoneproject-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
